controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\LoginController::login

register:
    path: /register
    controller: App\Controller\RegisterController::index

cars:
    path: /cars
    controller: App\Controller\RegisterController::index

admin:
    path: /admin
    controller: App\Controller\AdminController::index