controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
<<<<<<< HEAD
    type: attribute
=======
    type: attribute

garage:
    path: /Garage
    controller: App\Controller\GarageController::index

home:
    path: /home
    controller: App\Controller\HomeController::index
>>>>>>> 26421bb3a19d9a5861c635c7f79ec6f7cf84f689
